### ISSUE TITLE
Missing EKS custom signer

### ISSUE THREAD

**Issue by ayuspin** [PaloAltoNetworks/cn-series-helm#21]
Missing EKS "beta.eks.amazonaws.com/app-serving" custom signer in pan-mgmt-serviceaccount.yaml which is present in https://raw.githubusercontent.com/PaloAltoNetworks/Kubernetes/v3.0/pan-cn-k8s-service/eks/pan-mgmt-serviceaccount.yaml

```
19a20,21
  # Support custom signer
  - "beta.eks.amazonaws.com/app-serving"
```

**Comment by skrish-murt** [comment]
Updated the repo with the custom signer.
